config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('detail/<int:pk>', views.article_detail, name='detail_post'),
    path('all', views.AllArticleView.as_view(), name='all_post'),
    path('all/<int:pk>', views.article_category_view, name='all_post_with_category'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

pages/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='Category/photo')

    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('pages:all_post_with_category', args=[self.id])


class Article(models.Model):
    title = models.CharField(max_length=200)
    category = models.ManyToManyField(Category, related_name='category', null=True, blank=True)
    description = models.TextField()
    image = models.ImageField(upload_to='Article/photo')
    status = models.BooleanField(default=False)

    datetime_create = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('pages:detail_post', args=[self.id])


class Comment(models.Model):
    username = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comment')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comment')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='reply', null=True, blank=True)
    massage = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.massage)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', )

accounts/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.contrib import messages
from django.core.paginator import Paginator

from .models import Article, Category, Comment


class HomeView(generic.ListView):
    http_method_names = ['get']
    queryset = Article.objects.all()[:6]
    template_name = 'pages/home.html'
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()[:6]
        return context


class AllArticleView(generic.ListView):
    http_method_names = ['get']
    model = Article
    template_name = 'pages/all_post.html'
    context_object_name = 'article'
    paginate_by = 6


def article_category_view(request, pk):
    category = get_object_or_404(Category, id=pk)
    article = Article.objects.filter(category=category)
    paginator = Paginator(article, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'pages/all_post.html', {'article': page_obj})


def article_detail(request, pk):
    article = get_object_or_404(Article, id=pk)
    category = Category.objects.all()[:10]
    articles = Article.objects.all().order_by('-datetime_create')[:3]

    if request.method == 'POST':
        massage = request.POST.get('message')
        parent_id = request.POST.get('parent_id')

        Comment.objects.create(article=article, username=request.user, massage=massage, parent_id=parent_id)
        messages.success(request, 'Your comment was successfully ! ')
    return render(request, 'pages/detail_post.html',
                  {'article': article, 'articles': articles, 'category': category})

pages/templates/pages/all_post.html
{% extends '_base.html' %}

{% load static %}
All Article
{% block title %}

{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            {% for item in article %}
                <div class="col-lg-6">
                    <div class="card text-center mb-5">
                        <div class="card-header p-0">
                            <div class="blog-media">
                                <img src="{{ item.image.url }}" alt="" class="w-100">
                                <a href="#" class="badge badge-primary">#{{ item.category.first }}</a>
                            </div>
                        </div>~
                        <div class="card-body px-0">
                            <h5 class="card-title mb-2">{{ item.title }}</h5>
                            <small class="small text-muted">{{ item.datetime_modified }}
                                <span class="px-2">-</span>
                                <a href="#" class="text-muted">{{ item.comment.count }} Comments</a>
                            </small>
                            <p class="my-2">{{ item.description }}.</p>
                        </div>

                        <div class="card-footer p-0 text-center">
                            <a href="{{ item.get_absolute_url }}" class="btn btn-outline-dark btn-sm">READ
                                MORE</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-12">
                <nav class="pagination-wrap mt--35 mt-md--25 pb-5">
                    {% if page_obj.has_other_pages %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

pages/templates/pages/detail_post.html
{% extends '_base.html' %}

{% load static %}

{% block title %}

{% endblock %}

{% block content %}
    <section class="container">
        <div class="page-container">
            <div class="page-content">
                <div class="card">
                    <div class="card-header pt-0">
                        <h3 class="card-title mb-4">{{ article.title }}</h3>
                        <div class="blog-media mb-4">
                            <img src="{{ article.image.url }}" alt="" class="w-100">
                            <a href="#" class="badge badge-primary">#{{ article.category.first }}</a>
                        </div>
                        <small class="small text-muted">
                            <span>{{ article.datetime_modified }}</span>
                            <span class="px-2">·</span>
                            <a href="#" class="text-muted">32 Comments</a>
                        </small>
                    </div>
                    <div class="card-body border-top">
                        <p class="my-3">{{ article.description }}</p>
                    </div>

                    <div class="card-footer">
                        <h6 class="mt-5 mb-3 text-center"><a href="#" class="text-dark">Comments 4</a></h6>
                        <hr>
                        {% for comments in article.comment.all %}
                            {% if comments.parent == None %}
                                <ul>
                                    <li>
                                        <div class="author-thumb">
                                            <img src="{% static 'images/comment-author-01.jpg' %}"
                                                 alt="">
                                        </div>
                                        <div class="right-content">
                                            <h4>{{ comments.username }}</h4>
                                            <p>{{ comments.massage }}</p>
                                            <button class="btn btn-primary"
                                                    onclick="set_value({{ comments.id }})"
                                                    type="submit">Reply
                                            </button>
                                        </div>
                                    </li>
                                    {% for replys in comments.reply.all %}
                                        <li class="replied">
                                            <div class="author-thumb">
                                                <img src="{% static 'images/comment-author-02.jpg' %}"
                                                     alt="">
                                            </div>
                                            <div class="right-content">
                                                <h4>{{ replys.username }}</h4>
                                                <p>{{ replys.massage }}</p>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        {% endfor %}

                        <h6 class="mt-5 mb-3 text-center"><a href="#" class="text-dark">Write Your Comment</a></h6>
                        <hr>
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-lg-12">
                                    {% if request.user.is_authenticated %}
                                        <fieldset>
                                            <label>
                                                <input id="parent_id" type="hidden" name="parent_id"
                                                       value="">
                                            </label>
                                            <label for="message"></label>
                                            <textarea name="message" rows="6"
                                                      id="message"
                                                      placeholder="Type your comment"
                                                      required=""></textarea>
                                        </fieldset>
                                        </div>
                                        <div class="form-group col-12">
                                            <button class="btn btn-primary btn-block">Post Comment</button>
                                        </div>
                                    {% else %}
                                        <p class="warning">please <a href="{% url 'account_signup' %}">Create
                                            account</a> or
                                            <a href="{% url 'account_login' %}">login</a> in site.</p>
                                        </div>
                                    {% endif %}
                        </form>
                    </div>
                </div>

                <h6 class="mt-5 text-center">Related Posts</h6>
                <hr>
                <div class="row">
                    {% for article in articles %}
                        <div class="col-md-6 col-lg-4">
                            <div class="card mb-5">
                                <div class="card-header p-0">
                                    <div class="blog-media">
                                        <img src="{{ article.image.url }}" alt="" class="w-100">
                                        <a href="#" class="badge badge-primary">#{{ article.category.first }}</a>
                                    </div>
                                </div>
                                <div class="card-body px-0">
                                    <h6 class="card-title mb-2"><a href="{% url 'pages:detail_post' article.id %}"
                                                                   class="text-dark">{{ article.title }}</a>
                                    </h6>
                                    <small class="small text-muted">{{ article.datetime_modified }}
                                        <span class="px-2">-</span>
                                        <a href="#" class="text-muted">34 Comments</a>
                                    </small>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Sidebar -->
            <div class="page-sidebar">
                <h6 class=" ">Tags</h6>
                {% for catagorys in category %}
                    <a href="#" class="badge badge-primary m-1">#{{ catagorys.title }}</a>
                {% endfor %}
                <div class="ad-card d-flex text-center align-items-center justify-content-center mt-4">
                    <span href="#" class="font-weight-bold">ADS</span>
                </div>
            </div>
        </div>
    </section>

    <div class="instagram-wrapper mt-5">
        <div class="ig-id">
            <a href="javascript:void(0)">Follow @joe_mitchell On Instagram</a>
        </div>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-1.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-2.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-3.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-4.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-5.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-6.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
    </div>
    <script>
        function set_value(id) {
            document.getElementById('parent_id').value = id;
        }
    </script>
{% endblock %}

pages/templates/pages/home.html
{% extends '_base.html' %}

{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="container">
        <section>
            <div class="feature-posts">
                <h5 class="feature-post-item">
                    <span>Category</span>
                </h5>
                {% for categorys in category %}
                    <a href="{{ categorys.get_absolute_url }}" class="feature-post-item">
                        <img src="{{ categorys.image.url }}" class="w-100" alt="">
                        <div class="feature-post-caption">{{ categorys.title }}</div>
                    </a>
                {% endfor %}
            </div>
        </section>
        <hr>
        <div class="page-container">
            <div class="page-content">
                <hr>
                <div class="row">
                    {% for item in article %}
                        <div class="col-lg-6">
                            <div class="card text-center mb-5">
                                <div class="card-header p-0">
                                    <div class="blog-media">
                                        <img src="{{ item.image.url }}" alt="" class="w-100">
                                        <a href="#" class="badge badge-primary">#{{ item.category.first }}</a>
                                    </div>
                                </div>
                                <div class="card-body px-0">
                                    <h5 class="card-title mb-2">{{ item.title }}</h5>
                                    <small class="small text-muted">{{ item.datetime_modified }}
                                        <span class="px-2">-</span>
                                        <a href="#" class="text-muted">120 Comments</a>
                                    </small>
                                    <p class="my-2">{{ item.description }}.</p>
                                </div>

                                <div class="card-footer p-0 text-center">
                                    <a href="{{ item.get_absolute_url }}" class="btn btn-outline-dark btn-sm">READ
                                        MORE</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a href="{% url 'pages:all_post' %}">
                    <button class="btn btn-primary btn-block my-4">Load More Posts</button>
                </a>
            </div>

            <!-- Sidebar -->
            <div class="page-sidebar text-center">
                <h6 class="sidebar-title section-title mb-4 mt-3">About</h6>
                <img src="{% static 'imgs/avatar.jpg' %}" alt="" class="circle-100 mb-3">
                <div class="socials mb-3 mt-2">
                    <a href="javascript:void(0)"><i class="ti-facebook"></i></a>
                    <a href="javascript:void(0)"><i class="ti-twitter"></i></a>
                    <a href="javascript:void(0)"><i class="ti-pinterest-alt"></i></a>
                    <a href="javascript:void(0)"><i class="ti-instagram"></i></a>
                    <a href="javascript:void(0)"><i class="ti-youtube"></i></a>
                </div>
                <p>Consectetur adipisicing elit Possimus tempore facilis dolorum veniam impedit nobis. Quia, soluta
                    incidunt
                    nesciunt dolorem reiciendis iusto.</p>


                <h6 class="sidebar-title mt-5 mb-4">Newsletter</h6>
                <form action="">
                    <div class="subscribe-wrapper">
                        <input type="email" class="form-control" placeholder="Email Address">
                        <button type="submit" class="btn btn-primary"><i class="ti-location-arrow"></i></button>
                    </div>
                </form>

                <h6 class="sidebar-title mt-5 mb-4">Tags</h6>
                {% for categorys in category %}
                    <a href="javascript:void(0)" class="badge badge-primary m-1">#{{ categorys.title }}</a>
                {% endfor %}
                <hr>
                {% for articles in article %}
                    <div class="media text-left mb-4">
                        <a href="{% url 'pages:detail_post' articles.id %}" class="overlay-link"></a>
                        <img class="mr-3" src="{{ articles.image.url }}" width="100px"
                             alt="Generic placeholder image">
                        <div class="media-body">
                            <h6 class="mt-0">{{ articles.title }}</h6>
                            <p class="mb-2">{{ articles.description|truncatewords:3 }}</p>
                            <p class="text-muted small"><i
                                    class="ti-calendar pr-1"></i> {{ articles.datetime_modified }}</p>
                        </div>
                    </div>
                {% endfor %}
                <div class="ad-card d-flex text-center align-items-center justify-content-center">
                    <span href="#" class="font-weight-bold">ADS</span>
                </div>
            </div>
        </div>
    </div>

    <div class="instagram-wrapper mt-5">
        <div class="ig-id">
            <a href="javascript:void(0)">Follow @joe_mitchell On Instagram</a>
        </div>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-1.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-2.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-3.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-4.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-5.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
        <a href="javascript:void(0)" class="insta-item">
            <img src="{% static 'imgs/insta-6.jpg' %}" alt="" class="w-100">
            <div class="overlay">
                <span>
                    <i class="ti-heart"></i> 23
                </span>
                <span>
                    <i class="ti-comment"></i> 12
                </span>
            </div>
        </a>
    </div>

{% endblock %}

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'include/head.html' %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<!-- page First Navigation -->
{% include 'include/first_navbar.html' %}
<!-- End Of First Navigation -->
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="btn btn-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<!-- Page Second Navigation -->
{% include 'include/second_navbar.html' %}
<!-- End Of Page Second Navigation -->

<!-- page-header -->
<header class="page-header"></header>
<!-- end of page header -->

{% block content %}

{% endblock %}


<!-- Page Footer -->
<footer class="page-footer">
    {% include 'include/footer.html' %}
</footer>
<!-- End of Page Footer -->


<!-- Scripts -->
{% include 'include/scripts.html' %}
<!-- end Scripts -->

</body>
</html>

templates/include/first_navbar.html
{% load static %}
<nav class="navbar navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="{% static 'imgs/logo.svg' %}" alt="">
        </a>
        <div class="socials">
            <a href="javascript:void(0)"><i class="ti-facebook"></i></a>
            <a href="javascript:void(0)"><i class="ti-twitter"></i></a>
            <a href="javascript:void(0)"><i class="ti-pinterest-alt"></i></a>
            <a href="javascript:void(0)"><i class="ti-instagram"></i></a>
            <a href="javascript:void(0)"><i class="ti-youtube"></i></a>
        </div>
    </div>
</nav>

templates/include/footer.html
{% load static %}
<footer class="page-footer">
    <div class="container">
        <div class="row align-items-center justify-content-between">
            <div class="col-md-3 text-center text-md-left mb-3 mb-md-0">
                <img src="{% static 'imgs/logo.svg' %}" alt="" class="logo">
            </div>
            <div class="col-md-9 text-center text-md-right">
                <div class="socials">
                    <a href="javascript:void(0)" class="font-weight-bold text-muted mr-4"><i
                            class="ti-facebook pr-1"></i> 123,345</a>
                    <a href="javascript:void(0)" class="font-weight-bold text-muted mr-4"><i
                            class="ti-twitter pr-1"></i> 321,534</a>
                    <a href="javascript:void(0)" class="font-weight-bold text-muted mr-4"><i
                            class="ti-pinterest-alt pr-1"></i> 543,312</a>
                    <a href="javascript:void(0)" class="font-weight-bold text-muted mr-4"><i
                            class="ti-instagram pr-1"></i> 123,023</a>
                    <a href="javascript:void(0)" class="font-weight-bold text-muted mr-4"><i
                            class="ti-youtube pr-1"></i> 231,043</a>
                </div>
            </div>
        </div>
        <p class="border-top mb-0 mt-4 pt-3 small">&copy;
            <script>document.write(new Date().getFullYear())</script>
            , JoeBlog Created By <a href="https://www.devcrud.com" class="text-muted font-weight-bold" target="_blank">DevCrud.</a>
            All rights reserved
        </p>
    </div>
</footer>

templates/include/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Start your development with JoeBLog landing page.">
<meta name="author" content="Devcrud">
<title>JoeBLog | Free Bootstrap 4.3.x template</title>
<!-- font icons -->
<link rel="stylesheet" href="{% static 'vendors/themify-icons/css/themify-icons.css' %}">
<!-- Bootstrap + JoeBLog main styles -->
<link rel="stylesheet" href="{% static 'css/joeblog.css' %}">

templates/include/scripts.html
{% load static %}
<!-- core  -->
<script src="{% static 'vendors/jquery/jquery-3.4.1.js' %}"></script>
<script src="{% static 'vendors/bootstrap/bootstrap.bundle.js' %}"></script>

<!-- JoeBLog js -->
<script src="{% static 'js/joeblog.js' %}"></script>

templates/include/second_navbar.html
<nav class="navbar custom-navbar navbar-expand-md navbar-light bg-primary sticky-top">
    <div class="container">
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:all_post' %}">All Post</a>
                </li>
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <span>Hello {{ request.user.username }}</span> |
                        <span><a href="{% url 'account_logout' %}">Logout</a></span>
                    {% else %}
                        <snap><a href="{% url 'account_signup' %}">Sign Up</a></snap> |
                        <span><a href="{% url 'account_login' %}">Login</a></span>
                    {% endif %}
                </li>
            </ul>
            <div class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="components.html" class="ml-4 btn btn-dark mt-1 btn-sm">Components</a>
                </li>
            </div>
        </div>
    </div>
</nav>